services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./php/local_84_dev.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: framework
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3318:3306"
